### ISSUE TITLE
Control by EE_POSE

### ISSUE THREAD

**Issue by Chu4nQ1n** [chen37058/Grasp-with-the-Unitree-D1#1]
Hi,

Thanks for sharing this insightful demo on controlling the Unitree D1 robotic arm using `ctypes`! 

I’m currently exploring ways to control the D1 using `EE_POSE`, specifically for end-effector’s position and orientation. I would love to know if you have any experience or suggestions on using `EE_POSE` for this purpose. Any insights, methods, or challenges you encountered would be greatly appreciated!

Best regards,  
Chuan

**Comment by chen37058** [comment]
Hi Chuan,

I’m glad to hear that you found the demo helpful！

Regarding your question about controlling the D1 using EE_POSE, the Unitree D1 arm service interface documentation does mention methods for controlling the arm through end-effector pose. You can find more details in their developer documentation here: [Unitree D1 Arm Services](https://support.unitree.com/home/zh/developer/D1Arm_services).

For the end-effector pose control, the required data includes `pose_x`, `pose_y`, `pose_z`, along with the orientation parameters `roll`, `pitch`, and `yaw`. Although I haven’t personally used this method, I believe if you structure the data following the provided examples, it should work as expected.

Feel free to reach out if you encounter any issues while trying this approach!

**Comment by Chu4nQ1n** [comment]
Thank you for your response. I actually tried implementing EE_POSE control based on the documentation, but unfortunately, Unitree hasn’t provided the interface for EE_POSE control, which I have confirmed with their technical support team.

Therefore, achieving EE_POSE control requires a separate IK-solver, and I've encountered quite a challenge with Unitree D1’s URDF file, as each link’s coordinate axes appear disordered. Nonetheless, I truly appreciate your help!

**Comment by it5meyash** [comment]
Hi chen can we integrate lerobot library on unitree d1 arm?

**Comment by chen37058** [comment]
> Hi chen can we integrate lerobot library on unitree d1 arm?

Hi~ I'm not familiar with lerobot, but I'd suggest contacting Unitree's technical support for information on integrating third-party libraries with the D1 arm.

**Comment by it5meyash** [comment]
Hi chen thank you for your responce. Can you guide me on using your repo of d1 arm ?

**Comment by chen37058** [comment]
> Hi chen thank you for your responce. Can you guide me on using your repo of d1 arm ?

Of course! Feel free to ask any questions.

**Comment by it5meyash** [comment]
Of course! Feel free to ask any questions.

Can you please share your linkedin, gmail or any other social site.

**Comment by chen37058** [comment]
> Of course! Feel free to ask any questions.
> 
> Can you please share your linkedin, gmail or any other social site.

You can find them in the introduction on my GitHub homepage.
